name: Build YgoMaster

on:
  workflow_dispatch:  # Cho phép chạy workflow thủ công

jobs:
  build:
    runs-on: windows-latest  # Sử dụng môi trường Windows

    steps:
    # Bước 1: Lấy mã nguồn từ repository
    - name: Check out repository
      uses: actions/checkout@v3

    # Bước 2: Thiết lập môi trường .NET Framework (nếu cần)
    - name: Install .NET Framework Developer Pack
      run: |
        choco install dotnetfx --version=4.8.1
        choco install visualstudio2019community --package-parameters "--add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools"
        choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools"

    # Bước 3: Chạy Build.bat
    - name: Run Build.bat
      run: |
        echo Running Build.bat
        call Build.bat
      shell: cmd

    # Bước 4: Upload Artifact (kết quả build)
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: YgoMaster-Build
        path: ./bin  # Thay đổi path này thành thư mục output do Build.bat tạo ra
